apiVersion: 1

datasources:
  - name: InfluxDB-K6
    type: influxdb
    access: proxy
    url: http://k6-influxdb:8086
    database: k6
    user: k6
    secureJsonData:
      password: k6password
    jsonData:
      httpMode: GET
    isDefault: true
    editable: true