# Docker Compose for K6 Load Testing
# No need to install K6 locally - everything runs in containers

services:
  # K6 Load Testing Runner
  k6:
    image: grafana/k6:latest
    container_name: insight-k6-runner
    volumes:
      - .:/app/tests
      - ./results:/app/results
    working_dir: /app/tests
    environment:
      - TEST_HOST=${TEST_HOST:-http://host.docker.internal:8080}
      - JWT_TOKEN=${JWT_TOKEN:-dummy-token-for-non-auth-testing}
      - TEST_TYPE=${TEST_TYPE:-load}
    networks:
      - k6-network
    profiles:
      - manual  # Only start when specifically requested
    command: ["run", "--out", "json=/app/results/k6_results.json", "scenarios/mixed-load.js"]

  # InfluxDB v1.8 for storing K6 metrics (K6 built-in support)
  k6-influxdb:
    image: influxdb:1.8
    platform: linux/amd64
    container_name: insight-k6-influxdb
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=k6password
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    ports:
      - "8087:8086"  # Different port to avoid conflict with main InfluxDB
    volumes:
      - k6-influxdb-data:/var/lib/influxdb
    networks:
      - k6-network
    profiles:
      - metrics  # Only start when metrics collection needed

  # Grafana for visualizing K6 metrics (optional)
  k6-grafana:
    image: grafana/grafana:latest
    container_name: insight-k6-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=k6admin
      - GF_INSTALL_PLUGINS=grafana-k6-app
    ports:
      - "3001:3000"  # Different port to avoid conflict with main Grafana
    volumes:
      - k6-grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - k6-network
    profiles:
      - metrics  # Only start when metrics collection needed
    depends_on:
      - k6-influxdb

  # K6 Test Results Analyzer (custom service for analyzing results)
  k6-analyzer:
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    container_name: insight-k6-analyzer  
    volumes:
      - ./results:/app/results
    environment:
      - RESULTS_DIR=/app/results
    networks:
      - k6-network
    profiles:
      - analysis  # Only start when analysis needed

networks:
  k6-network:
    driver: bridge
    name: insight-k6-network

volumes:
  k6-influxdb-data:
    name: insight-k6-influxdb-data
  k6-influxdb-config:
    name: insight-k6-influxdb-config
  k6-grafana-data:
    name: insight-k6-grafana-data